// Academy videos catalogue — shared by the Academy page and the global search.

export interface Video {
  id: string;
  title: string;
  description: string;
  duration: string;
  category: string;
  level: 'Iniciante' | 'Intermédio' | 'Avançado';
  topics: string[];
}

export const VIDEOS: Video[] = [
  {
    id: 'v01',
    title: 'Primeiros Passos com o iComply',
    description: 'Visão geral da plataforma, navegação, configuração inicial da organização e criação do primeiro utilizador.',
    duration: '8 min',
    category: 'Introdução',
    level: 'Iniciante',
    topics: ['Dashboard', 'Perfil', 'Organização'],
  },
  {
    id: 'v02',
    title: 'Gestão de Riscos — Criar e Avaliar Riscos',
    description: 'Como criar riscos, definir probabilidade e impacto, atribuir responsáveis e monitorizar o mapa de riscos.',
    duration: '10 min',
    category: 'Riscos',
    level: 'Iniciante',
    topics: ['Registo de riscos', 'Mapa de calor', 'Avaliação'],
  },
  {
    id: 'v03',
    title: 'Gestão de Riscos — Tratamento e Planos de Acção',
    description: 'Definir estratégias de tratamento (aceitar, mitigar, transferir, eliminar) e criar planos de acção associados.',
    duration: '9 min',
    category: 'Riscos',
    level: 'Intermédio',
    topics: ['Tratamento', 'CAPA', 'Monitorização'],
  },
  {
    id: 'v04',
    title: 'Gestão Documental — Políticas e Procedimentos',
    description: 'Criar, versionar e publicar políticas. Gerir o ciclo de revisão e obter aprovações.',
    duration: '8 min',
    category: 'Documentos',
    level: 'Iniciante',
    topics: ['Políticas', 'Versões', 'Aprovações'],
  },
  {
    id: 'v05',
    title: 'Auditorias Internas — Planeamento e Execução',
    description: 'Criar um plano de auditoria, atribuir auditores, registar constatações e emitir o relatório final.',
    duration: '12 min',
    category: 'Auditorias',
    level: 'Intermédio',
    topics: ['Plano de auditoria', 'Constatações', 'Relatório'],
  },
  {
    id: 'v06',
    title: 'RGPD — ROPA e Avaliações de Impacto (AIPD)',
    description: 'Registar actividades de tratamento, gerir pedidos de titulares e conduzir avaliações de impacto.',
    duration: '11 min',
    category: 'RGPD',
    level: 'Intermédio',
    topics: ['ROPA', 'AIPD', 'Pedidos de titulares'],
  },
  {
    id: 'v07',
    title: 'Gestão de Tarefas e Dependências',
    description: 'Criar tarefas, definir dependências, usar a vista Kanban e o Gantt para acompanhar o progresso.',
    duration: '9 min',
    category: 'Tarefas',
    level: 'Iniciante',
    topics: ['Kanban', 'Gantt', 'Dependências'],
  },
  {
    id: 'v08',
    title: 'Gestão de Evidências e Recolha Automática',
    description: 'Carregar evidências manualmente, configurar integrações automáticas e mapear evidências a controlos.',
    duration: '10 min',
    category: 'Evidências',
    level: 'Intermédio',
    topics: ['Upload', 'Integrações', 'Controlos'],
  },
  {
    id: 'v09',
    title: 'Conformidade NIS2 — Do Diagnóstico à Implementação',
    description: 'Realizar o diagnóstico NIS2, priorizar requisitos e acompanhar o plano de implementação.',
    duration: '13 min',
    category: 'NIS2',
    level: 'Avançado',
    topics: ['Diagnóstico', 'Requisitos', 'Relatório NIS2'],
  },
  {
    id: 'v10',
    title: 'ISO 27001 — Gestão de Controlos e Declaração de Aplicabilidade',
    description: 'Gerir os controlos do Anexo A, documentar a Declaração de Aplicabilidade (SoA) e preparar a auditoria.',
    duration: '14 min',
    category: 'ISO 27001',
    level: 'Avançado',
    topics: ['SoA', 'Anexo A', 'Auditoria de certificação'],
  },
  {
    id: 'v11',
    title: 'Dashboard Executivo — Personalizar e Interpretar Métricas',
    description: 'Configurar widgets, interpretar indicadores-chave e partilhar relatórios com a gestão de topo.',
    duration: '7 min',
    category: 'Dashboard',
    level: 'Iniciante',
    topics: ['Widgets', 'KPIs', 'Relatórios'],
  },
  {
    id: 'v12',
    title: 'Motor de Automações — Criar Fluxos de Trabalho',
    description: 'Criar regras de automação baseadas em eventos, condições e acções para reduzir trabalho manual.',
    duration: '11 min',
    category: 'Automações',
    level: 'Avançado',
    topics: ['Regras', 'Triggers', 'Acções automáticas'],
  },
  {
    id: 'v13',
    title: 'Portal de Auditores Externos — Colaboração Segura',
    description: 'Configurar o portal de auditores externos, partilhar evidências e gerir acessos temporários.',
    duration: '8 min',
    category: 'Auditorias',
    level: 'Intermédio',
    topics: ['Portal externo', 'Partilha', 'Acessos'],
  },
  {
    id: 'v14',
    title: 'Formação de Colaboradores — Módulos e Questionários',
    description: 'Criar módulos de formação, atribuir a colaboradores e monitorizar a taxa de conclusão.',
    duration: '9 min',
    category: 'Formação',
    level: 'Intermédio',
    topics: ['Módulos', 'Questionários', 'Certificados'],
  },
  {
    id: 'v15',
    title: 'iGuard — Monitorização de Dispositivos',
    description: 'Instalar o agente iGuard, interpretar o score de conformidade dos dispositivos e gerir alertas.',
    duration: '8 min',
    category: 'iGuard',
    level: 'Iniciante',
    topics: ['Instalação', 'Score', 'Alertas'],
  },
  {
    id: 'v16',
    title: 'Integration Hub — Ligar Ferramentas Externas',
    description: 'Configurar integrações com IAM, HRIS, MDM e outras ferramentas via Truto.',
    duration: '10 min',
    category: 'Integrações',
    level: 'Avançado',
    topics: ['Truto', 'IAM', 'HRIS', 'MDM'],
  },
  {
    id: 'v17',
    title: 'DORA — Registo de Informação e Incidentes TIC',
    description: 'Preencher o Registo de Informação DORA, reportar incidentes TIC e gerir prestadores críticos.',
    duration: '12 min',
    category: 'DORA',
    level: 'Avançado',
    topics: ['RoI', 'Incidentes TIC', 'Terceiros críticos'],
  },
  {
    id: 'v18',
    title: 'Gestão de Utilizadores, Papéis e Permissões',
    description: 'Criar utilizadores, definir papéis (RBAC), gerir convites e configurar SSO.',
    duration: '8 min',
    category: 'Administração',
    level: 'Intermédio',
    topics: ['RBAC', 'Convites', 'SSO'],
  },
  {
    id: 'v19',
    title: 'Regulatory Intelligence — Acompanhar Alterações Regulatórias',
    description: 'Usar o feed regulatório para monitorizar novas regulamentações e avaliar o seu impacto.',
    duration: '7 min',
    category: 'Inteligência Regulatória',
    level: 'Intermédio',
    topics: ['Feed', 'Alertas', 'Impacto'],
  },
  {
    id: 'v20',
    title: 'Relatórios para o Órgão de Gestão',
    description: 'Gerar relatórios executivos, preparar atas de gestão e documentar decisões do Conselho.',
    duration: '9 min',
    category: 'Relatórios',
    level: 'Avançado',
    topics: ['Board reports', 'Atas', 'KPIs executivos'],
  },
];
